import os


SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_META_DATABASE_URI"]

FEATURE_FLAGS = {
    "ALERT_REPORTS": False,
}

WTF_CSRF_ENABLED = True
ENABLE_PROXY_FIX = True
